CREATE TABLE public.contract
(
    contract_id serial NOT NULL,
    pursuant_law character varying(500),
    contract_no character varying(20) NOT NULL,
    contract_establishment_date date NOT NULL,
    seller_corporate_id int4range NOT NULL,
    buyer_corporate_id int4range NOT NULL,
    description_commodity character varying(500),
    contract_vat integer,
    contract_value integer,
    currency character varying(20),
    amount_reduction_tolerance character varying(2),
    tolerance_increase_amount character varying(2),
    delivery_vehicle character varying(500),
    delivery_term character varying(300),
    delivery_deadline date,
    place_delivery character varying(100),
    delivery_location character varying(100),
    product_quality character varying(300),
    terms_of_exchange character varying(300),
    goods_warranty character varying(300),
    payment_methods integer,
    transfer_payments character varying(100),
    lc_payment character varying(100),
    lc_id int4range,
    payment_term_lc character varying(100),
    license_id int4range,
    late_payment_interest_rate integer,
    cargo_insurance character varying(500),
    obligations_buyer character varying(1000),
    obligations_seller character varying(1000),
    regulations_penalties_and_contract_compensation character varying(1000),
    dispute_settlement_procedures character varying(1000),
    case_of_force_majeure character varying(1000),
    validity_contract character varying(1000),
    general_terms character varying(1000),
    fee_rules_id int4range,
    proposal_release_lc_id int4range,
    created_date timestamp with time zone,
    created_by character varying,
    last_modified_by character varying,
    last_modified_date timestamp with time zone,
    CONSTRAINT "PK_contract_id" PRIMARY KEY (contract_id),
    CONSTRAINT contract_no UNIQUE (contract_no)
);

ALTER TABLE IF EXISTS public.contract
    OWNER to postgre;