ALTER TABLE public.corporate ADD signature_serial varchar NULL;
ALTER TABLE public.corporate ADD signature varchar NULL;
COMMENT ON COLUMN public.corporate.signature IS 'chu ky';
ALTER TABLE public.corporate ADD signature_subscriber_name varchar NULL;
COMMENT ON COLUMN public.corporate.signature_subscriber_name IS 'ten thue bao';
ALTER TABLE public.corporate ADD signature_time varchar NULL;
COMMENT ON COLUMN public.corporate.signature_time IS 'thoio gian';
ALTER TABLE public.corporate ADD signature_certificate varchar NULL;
COMMENT ON COLUMN public.corporate.signature_certificate IS 'chung chi';
ALTER TABLE public.corporate ADD signature_expiration_date date NULL;
COMMENT ON COLUMN public.corporate.signature_expiration_date IS 'ngay het hieu luc';
ALTER TABLE public.corporate ADD signature_value_date date NULL;
COMMENT ON COLUMN public.corporate.signature_value_date IS 'ngay hieu luc';
ALTER TABLE public.corporate ADD signature_value varchar NULL;
COMMENT ON COLUMN public.corporate.signature_value IS 'hieu luc trong ';
ALTER TABLE public.corporate ADD signature_release_by varchar NULL;
COMMENT ON COLUMN public.corporate.signature_release_by IS 'nguoi phat hanh';
ALTER TABLE public.corporate ADD signature_tax_code varchar NULL;
COMMENT ON COLUMN public.corporate.signature_tax_code IS 'ma so thue';
