INSERT INTO public.financing_limit (id,created_by,created_date,last_modified_by,last_modified_date,bank_id,type_limit,contract_number_limit,date_range,expiration_date,money_type,description_of_transactions,request_a_refund,total_zoning_limit,total_commitment_limit,total_disbursement_amount,total_repayment_amount,availability_limit,financing_limit_code,status,total_limit,number_of_changes,sponsor_bank_id) VALUES
    (11, 'admin','2022-04-11 15:53:48.084','0104128565615','2022-04-15 19:33:08.809',1,'L/C nội địa','VPB1256','2022-04-15','2022-04-19','VND','description',false,12000000,25000000,20000000,10000000,-22000000,'HMVCB110422963',1,25000000,2,1);

INSERT INTO public.financing_limit_transaction (financing_limit_id,sponsor_offer_code,lc_number,revised_sponsorship_request_code_lc,modification_lc_code,transaction_code_presented,status_transaction_presented,"period",financing_date,loan_maturity_date,zoning_limit,commitment_limit,disbursement_amount,repayment_amount,created_by,created_date,last_modified_by,last_modified_date) VALUES
                                                                                                                                                                                                                                                                                                                                                                                                (11,'UPACLC123',NULL,NULL,NULL,NULL,NULL,'9m',NULL,NULL,10000000,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
                                                                                                                                                                                                                                                                                                                                                                                                (11,'UPACLC123_002','LC123',NULL,NULL,NULL,NULL,'9m',NULL,NULL,0,10000000,NULL,NULL,NULL,NULL,NULL,NULL),
                                                                                                                                                                                                                                                                                                                                                                                                (11,NULL,'LC123','UPACLCTUCHINH_001',NULL,NULL,NULL,'4m',NULL,NULL,2000000,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
                                                                                                                                                                                                                                                                                                                                                                                                (11,NULL,'LC123','UPACLCTUCHINH_001','LCCODE_001','',NULL,'6m',NULL,NULL,NULL,3000000,NULL,NULL,NULL,NULL,NULL,NULL),
                                                                                                                                                                                                                                                                                                                                                                                                (11,NULL,'LC123',NULL,'LCCODE_002',NULL,NULL,'6m',NULL,NULL,NULL,2000000,NULL,NULL,NULL,NULL,NULL,NULL),
                                                                                                                                                                                                                                                                                                                                                                                                (11,NULL,'LC123',NULL,NULL,'XUATTRINHCODE_001','NHTT THANH TOAN CHO NHTB',NULL,'2022-04-01','2022-04-15',NULL,10000000,10000000,NULL,NULL,NULL,NULL,NULL),
                                                                                                                                                                                                                                                                                                                                                                                                (11,NULL,'LC123',NULL,NULL,'XUATTRINHCODE_001','NHTT THANH TOAN CHO NHPH',NULL,'2022-04-01','2022-04-15',NULL,NULL,10000000,10000000,NULL,NULL,NULL,NULL);